//! RS256 access-token issuance and verification. The signing key is an RSA
//! keypair (generated by the auth service and persisted); public keys are
//! exposed via JWKS so external OIDC relying parties can verify without a secret.

use std::collections::HashMap;

use chrono::Utc;
use jsonwebtoken::{decode, decode_header, encode, Algorithm, DecodingKey, EncodingKey, Header, Validation};
use rand::RngCore;
use rsa::pkcs1::EncodeRsaPrivateKey;
use rsa::pkcs8::{EncodePublicKey, LineEnding};
use rsa::{RsaPrivateKey, RsaPublicKey};
use serde::{Deserialize, Serialize};

/// Generate a random 128-bit token id (hex).
fn gen_jti() -> String {
    let mut b = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut b);
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

/// Generate a fresh 2048-bit RSA keypair: `(kid, private_pem_pkcs1, public_pem_spki)`.
pub fn generate_rsa_keypair() -> Result<(String, String, String), JwtError> {
    let mut rng = rand::thread_rng();
    let priv_key = RsaPrivateKey::new(&mut rng, 2048).map_err(|_| JwtError::Key)?;
    let pub_key = RsaPublicKey::from(&priv_key);
    let private_pem = priv_key
        .to_pkcs1_pem(LineEnding::LF)
        .map_err(|_| JwtError::Key)?
        .to_string();
    let public_pem = pub_key
        .to_public_key_pem(LineEnding::LF)
        .map_err(|_| JwtError::Key)?;
    Ok((gen_jti(), private_pem, public_pem))
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String,
    pub email: String,
    pub iss: String,
    pub jti: String, // token id — used for access-token revocation
    pub iat: i64,
    pub exp: i64,
    // "access" for a normal access token; empty on the mfa/legacy path. Gives an
    // access token a positive type marker so an OIDC ID token (signed by the same
    // key, sharing the issuer) can never be replayed on the access-token path.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub token_use: String,
    // Empty for a normal access token; "mfa" for the short-lived token issued
    // between the password and TOTP steps of a 2FA login. An mfa token must
    // never be accepted as a bearer/access token.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub purpose: String,
    // M6: the tenant (and optional project) the token is bound to. Empty on the
    // legacy/mfa path; a normal access token always carries a tenant.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub tenant_id: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub project_id: String,
}

#[derive(Debug, thiserror::Error)]
pub enum JwtError {
    #[error("invalid signing key")]
    Key,
    #[error("token encode failed")]
    Encode,
    #[error("invalid or expired token")]
    Invalid,
}

#[derive(Clone)]
pub struct JwtManager {
    active_kid: String,
    enc: EncodingKey,
    verifiers: HashMap<String, DecodingKey>, // kid -> public key (active + rotated)
    issuer: String,
    access_ttl_secs: i64,
}

impl JwtManager {
    /// Build from PEM keys. `private_pem` is the active signer (PKCS#1);
    /// `public_pems` maps kid -> SPKI public PEM and must include `active_kid`.
    pub fn from_pem(
        active_kid: String,
        private_pem: &str,
        public_pems: &HashMap<String, String>,
        issuer: String,
        access_ttl_secs: i64,
    ) -> Result<Self, JwtError> {
        let enc = EncodingKey::from_rsa_pem(private_pem.as_bytes()).map_err(|_| JwtError::Key)?;
        let mut verifiers = HashMap::with_capacity(public_pems.len());
        for (kid, pem) in public_pems {
            let dk = DecodingKey::from_rsa_pem(pem.as_bytes()).map_err(|_| JwtError::Key)?;
            verifiers.insert(kid.clone(), dk);
        }
        if !verifiers.contains_key(&active_kid) {
            return Err(JwtError::Key);
        }
        Ok(Self { active_kid, enc, verifiers, issuer, access_ttl_secs })
    }

    pub fn access_ttl_secs(&self) -> i64 {
        self.access_ttl_secs
    }

    pub fn issue(&self, user_id: &str, email: &str, tenant_id: &str, project_id: &str) -> Result<String, JwtError> {
        let now = Utc::now().timestamp();
        let claims = Claims {
            sub: user_id.to_string(),
            email: email.to_string(),
            iss: self.issuer.clone(),
            jti: gen_jti(),
            iat: now,
            exp: now + self.access_ttl_secs,
            token_use: "access".to_string(),
            purpose: String::new(),
            tenant_id: tenant_id.to_string(),
            project_id: project_id.to_string(),
        };
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(self.active_kid.clone());
        encode(&header, &claims, &self.enc).map_err(|_| JwtError::Encode)
    }

    /// Sign a short-lived token proving the password step of a 2FA login passed.
    /// It carries purpose="mfa" and no jti (not an access token); LoginTotp
    /// exchanges it + a TOTP/recovery code for a real token pair.
    pub fn issue_mfa(&self, user_id: &str, ttl_secs: i64) -> Result<String, JwtError> {
        let now = Utc::now().timestamp();
        let claims = Claims {
            sub: user_id.to_string(),
            email: String::new(),
            iss: self.issuer.clone(),
            jti: String::new(),
            iat: now,
            exp: now + ttl_secs,
            token_use: String::new(),
            purpose: "mfa".to_string(),
            tenant_id: String::new(),
            project_id: String::new(),
        };
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(self.active_kid.clone());
        encode(&header, &claims, &self.enc).map_err(|_| JwtError::Encode)
    }

    /// Sign an OIDC ID token (RS256) for the given subject/audience with an
    /// optional nonce. `issuer` is the public OIDC issuer URL.
    pub fn issue_id_token(
        &self,
        sub: &str,
        email: &str,
        audience: &str,
        nonce: &str,
        issuer: &str,
    ) -> Result<String, JwtError> {
        let now = Utc::now().timestamp();
        let mut claims = serde_json::json!({
            "iss": issuer,
            "sub": sub,
            "aud": audience,
            "email": email,
            "iat": now,
            "exp": now + self.access_ttl_secs,
        });
        if !nonce.is_empty() {
            claims["nonce"] = serde_json::Value::String(nonce.to_string());
        }
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(self.active_kid.clone());
        encode(&header, &claims, &self.enc).map_err(|_| JwtError::Encode)
    }

    pub fn parse(&self, token: &str) -> Result<Claims, JwtError> {
        let kid = decode_header(token)
            .map_err(|_| JwtError::Invalid)?
            .kid
            .ok_or(JwtError::Invalid)?;
        let dk = self.verifiers.get(&kid).ok_or(JwtError::Invalid)?;
        let mut validation = Validation::new(Algorithm::RS256);
        validation.set_issuer(&[self.issuer.clone()]);
        decode::<Claims>(token, dk, &validation)
            .map(|data| data.claims)
            .map_err(|_| JwtError::Invalid)
    }

    /// Validate a token AND assert it is a bearer access token — not an MFA token
    /// and not an OIDC ID token. Access tokens always carry a jti and (after this
    /// change) token_use="access"; ID tokens carry neither. This makes the
    /// rejection explicit/by-design rather than relying on `jti` being a required
    /// field that an ID token happens to lack.
    pub fn parse_access(&self, token: &str) -> Result<Claims, JwtError> {
        let claims = self.parse(token)?;
        if !claims.purpose.is_empty() {
            return Err(JwtError::Invalid);
        }
        if claims.jti.is_empty() {
            return Err(JwtError::Invalid);
        }
        if !claims.token_use.is_empty() && claims.token_use != "access" {
            return Err(JwtError::Invalid);
        }
        Ok(claims)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mgr(ttl: i64) -> JwtManager {
        let (kid, priv_pem, pub_pem) = generate_rsa_keypair().unwrap();
        let mut pubs = HashMap::new();
        pubs.insert(kid.clone(), pub_pem);
        JwtManager::from_pem(kid, &priv_pem, &pubs, "iam-auth".into(), ttl).unwrap()
    }

    #[test]
    fn issue_and_parse() {
        let m = mgr(60);
        let tok = m.issue("user-123", "a@b.com", "", "").unwrap();
        let claims = m.parse(&tok).unwrap();
        assert_eq!(claims.sub, "user-123");
        assert_eq!(claims.email, "a@b.com");
    }

    #[test]
    fn rejects_tampered() {
        let m = mgr(60);
        let tok = m.issue("user-123", "a@b.com", "", "").unwrap();
        assert!(m.parse(&format!("{tok}x")).is_err());
    }

    #[test]
    fn rejects_expired() {
        let m = mgr(-3600);
        let tok = m.issue("user-123", "a@b.com", "", "").unwrap();
        assert!(m.parse(&tok).is_err());
    }

    #[test]
    fn rejects_token_from_other_key() {
        let a = mgr(60);
        let b = mgr(60);
        let tok = a.issue("user-123", "a@b.com", "", "").unwrap();
        assert!(b.parse(&tok).is_err());
    }

    // An OIDC ID token shares the signing key and issuer with access tokens but
    // carries no jti and no token_use="access"; parse_access must reject it so it
    // can't be replayed as a bearer token (regression for the token-confusion gap
    // that Go was exposed to).
    #[test]
    fn parse_access_rejects_id_token() {
        let m = mgr(60);
        // Issue with the manager's own issuer so the issuer check would pass —
        // only the access-token type guard may reject it.
        let id = m
            .issue_id_token("user-123", "a@b.com", "some-client", "nonce-1", "iam-auth")
            .unwrap();
        assert!(m.parse_access(&id).is_err());
    }

    #[test]
    fn parse_access_rejects_mfa() {
        let m = mgr(60);
        let t = m.issue_mfa("user-123", 60).unwrap();
        assert!(m.parse_access(&t).is_err());
    }

    #[test]
    fn parse_access_accepts_access_token() {
        let m = mgr(60);
        let t = m.issue("user-123", "a@b.com", "tenant-1", "").unwrap();
        let c = m.parse_access(&t).unwrap();
        assert_eq!(c.token_use, "access");
    }

    // jsonwebtoken's default Validation leeway is 60s, so a token expired by less
    // than that still validates (tolerates clock skew) while one expired well
    // beyond it does not. Confirms finding #4 is already handled in Rust.
    #[test]
    fn parse_tolerates_small_clock_skew() {
        let within = mgr(-30);
        let t = within.issue("user-123", "a@b.com", "", "").unwrap();
        assert!(within.parse(&t).is_ok());

        let beyond = mgr(-3600);
        let t2 = beyond.issue("user-123", "a@b.com", "", "").unwrap();
        assert!(beyond.parse(&t2).is_err());
    }
}
