//! RS256 access-token issuance and verification. The signing key is an RSA
//! keypair (generated by the auth service and persisted); public keys are
//! exposed via JWKS so external OIDC relying parties can verify without a secret.

use std::collections::HashMap;

use chrono::Utc;
use jsonwebtoken::{decode, decode_header, encode, Algorithm, DecodingKey, EncodingKey, Header, Validation};
use rand::RngCore;
use rsa::pkcs1::EncodeRsaPrivateKey;
use rsa::pkcs8::{EncodePublicKey, LineEnding};
use rsa::{RsaPrivateKey, RsaPublicKey};
use serde::{Deserialize, Serialize};

/// Generate a random 128-bit token id (hex).
fn gen_jti() -> String {
    let mut b = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut b);
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

/// Generate a fresh 2048-bit RSA keypair: `(kid, private_pem_pkcs1, public_pem_spki)`.
pub fn generate_rsa_keypair() -> Result<(String, String, String), JwtError> {
    let mut rng = rand::thread_rng();
    let priv_key = RsaPrivateKey::new(&mut rng, 2048).map_err(|_| JwtError::Key)?;
    let pub_key = RsaPublicKey::from(&priv_key);
    let private_pem = priv_key
        .to_pkcs1_pem(LineEnding::LF)
        .map_err(|_| JwtError::Key)?
        .to_string();
    let public_pem = pub_key
        .to_public_key_pem(LineEnding::LF)
        .map_err(|_| JwtError::Key)?;
    Ok((gen_jti(), private_pem, public_pem))
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String,
    pub email: String,
    pub iss: String,
    pub jti: String, // token id — used for access-token revocation
    pub iat: i64,
    pub exp: i64,
}

#[derive(Debug, thiserror::Error)]
pub enum JwtError {
    #[error("invalid signing key")]
    Key,
    #[error("token encode failed")]
    Encode,
    #[error("invalid or expired token")]
    Invalid,
}

#[derive(Clone)]
pub struct JwtManager {
    active_kid: String,
    enc: EncodingKey,
    verifiers: HashMap<String, DecodingKey>, // kid -> public key (active + rotated)
    issuer: String,
    access_ttl_secs: i64,
}

impl JwtManager {
    /// Build from PEM keys. `private_pem` is the active signer (PKCS#1);
    /// `public_pems` maps kid -> SPKI public PEM and must include `active_kid`.
    pub fn from_pem(
        active_kid: String,
        private_pem: &str,
        public_pems: &HashMap<String, String>,
        issuer: String,
        access_ttl_secs: i64,
    ) -> Result<Self, JwtError> {
        let enc = EncodingKey::from_rsa_pem(private_pem.as_bytes()).map_err(|_| JwtError::Key)?;
        let mut verifiers = HashMap::with_capacity(public_pems.len());
        for (kid, pem) in public_pems {
            let dk = DecodingKey::from_rsa_pem(pem.as_bytes()).map_err(|_| JwtError::Key)?;
            verifiers.insert(kid.clone(), dk);
        }
        if !verifiers.contains_key(&active_kid) {
            return Err(JwtError::Key);
        }
        Ok(Self { active_kid, enc, verifiers, issuer, access_ttl_secs })
    }

    pub fn access_ttl_secs(&self) -> i64 {
        self.access_ttl_secs
    }

    pub fn issue(&self, user_id: &str, email: &str) -> Result<String, JwtError> {
        let now = Utc::now().timestamp();
        let claims = Claims {
            sub: user_id.to_string(),
            email: email.to_string(),
            iss: self.issuer.clone(),
            jti: gen_jti(),
            iat: now,
            exp: now + self.access_ttl_secs,
        };
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(self.active_kid.clone());
        encode(&header, &claims, &self.enc).map_err(|_| JwtError::Encode)
    }

    /// Sign an OIDC ID token (RS256) for the given subject/audience with an
    /// optional nonce. `issuer` is the public OIDC issuer URL.
    pub fn issue_id_token(
        &self,
        sub: &str,
        email: &str,
        audience: &str,
        nonce: &str,
        issuer: &str,
    ) -> Result<String, JwtError> {
        let now = Utc::now().timestamp();
        let mut claims = serde_json::json!({
            "iss": issuer,
            "sub": sub,
            "aud": audience,
            "email": email,
            "iat": now,
            "exp": now + self.access_ttl_secs,
        });
        if !nonce.is_empty() {
            claims["nonce"] = serde_json::Value::String(nonce.to_string());
        }
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(self.active_kid.clone());
        encode(&header, &claims, &self.enc).map_err(|_| JwtError::Encode)
    }

    pub fn parse(&self, token: &str) -> Result<Claims, JwtError> {
        let kid = decode_header(token)
            .map_err(|_| JwtError::Invalid)?
            .kid
            .ok_or(JwtError::Invalid)?;
        let dk = self.verifiers.get(&kid).ok_or(JwtError::Invalid)?;
        let mut validation = Validation::new(Algorithm::RS256);
        validation.set_issuer(&[self.issuer.clone()]);
        decode::<Claims>(token, dk, &validation)
            .map(|data| data.claims)
            .map_err(|_| JwtError::Invalid)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mgr(ttl: i64) -> JwtManager {
        let (kid, priv_pem, pub_pem) = generate_rsa_keypair().unwrap();
        let mut pubs = HashMap::new();
        pubs.insert(kid.clone(), pub_pem);
        JwtManager::from_pem(kid, &priv_pem, &pubs, "iam-auth".into(), ttl).unwrap()
    }

    #[test]
    fn issue_and_parse() {
        let m = mgr(60);
        let tok = m.issue("user-123", "a@b.com").unwrap();
        let claims = m.parse(&tok).unwrap();
        assert_eq!(claims.sub, "user-123");
        assert_eq!(claims.email, "a@b.com");
    }

    #[test]
    fn rejects_tampered() {
        let m = mgr(60);
        let tok = m.issue("user-123", "a@b.com").unwrap();
        assert!(m.parse(&format!("{tok}x")).is_err());
    }

    #[test]
    fn rejects_expired() {
        let m = mgr(-3600);
        let tok = m.issue("user-123", "a@b.com").unwrap();
        assert!(m.parse(&tok).is_err());
    }

    #[test]
    fn rejects_token_from_other_key() {
        let a = mgr(60);
        let b = mgr(60);
        let tok = a.issue("user-123", "a@b.com").unwrap();
        assert!(b.parse(&tok).is_err());
    }
}
